version: "3"
services:
  server:
    build: .
    container_name: bia
    ports:
      - 80:8080
    environment:
      DB_USER: postgres
      DB_PWD: $nM01$jDl[MFdFeO+*n584rz-QZk
      DB_HOST: bia-db.cp8oyae2mpyk.us-east-1.rds.amazonaws.com
      DB_PORT: 5432
